import importlib

def test_test_scenarios_surface():
    module = importlib.import_module("core.forecast_ai.tests.test_scenarios")
    assert hasattr(module, "setUp")
    assert hasattr(module, "test_add_modifier")
    assert hasattr(module, "test_set_modifier")
    assert hasattr(module, "test_multiply_modifier")
    assert hasattr(module, "test_validate_modifier")
    assert hasattr(module, "setUp")
    assert hasattr(module, "test_builtin_scenarios_exist")
    assert hasattr(module, "test_baseline_not_registered")
    assert hasattr(module, "test_register_custom_scenario")
    assert hasattr(module, "setUp")
    assert hasattr(module, "test_baseline_no_change")
    assert hasattr(module, "test_training_scenario")
    assert hasattr(module, "test_staff_shortage_scenario")
    assert hasattr(module, "test_multiple_scenarios")
    assert hasattr(module, "test_priority_ordering")
    assert hasattr(module, "test_scheduling")
    assert hasattr(module, "test_immutability")
    assert hasattr(module, "test_inactive_scenario")
    assert hasattr(module, "test_validate_scenario")
    assert hasattr(module, "TestModifiers")
    assert hasattr(module, "TestScenarioRegistry")
    assert hasattr(module, "TestScenarioManager")
