import importlib

def test_test_trends_surface():
    module = importlib.import_module("core.forecast_ai.tests.test_trends")
    assert hasattr(module, "test_mean")
    assert hasattr(module, "test_median")
    assert hasattr(module, "test_slope")
    assert hasattr(module, "test_moving_average")
    assert hasattr(module, "test_oscillation")
    assert hasattr(module, "test_spike")
    assert hasattr(module, "test_recovery")
    assert hasattr(module, "test_plateau")
    assert hasattr(module, "test_stable")
    assert hasattr(module, "test_analyze_increasing")
    assert hasattr(module, "test_analyze_decreasing")
    assert hasattr(module, "test_analyze_oscillation")
    assert hasattr(module, "test_engine")
    assert hasattr(module, "test_formatter")
    assert hasattr(module, "TestStatistics")
    assert hasattr(module, "TestPatternDetector")
    assert hasattr(module, "TestTrendAnalyzer")
    assert hasattr(module, "TestTrendEngine")
    assert hasattr(module, "TestTrendFormatter")
