import importlib

def test_test_analytics_engines_surface():
    module = importlib.import_module("core.forecast_ai.tests.test_analytics_engines")
    assert hasattr(module, "generate")
    assert hasattr(module, "analyze")
    assert hasattr(module, "analyze")
    assert hasattr(module, "test_report_missing_parameters")
    assert hasattr(module, "test_report_success")
    assert hasattr(module, "test_sensitivity_missing_state")
    assert hasattr(module, "test_sensitivity_success")
    assert hasattr(module, "test_trend_missing_series")
    assert hasattr(module, "test_trend_success")
    assert hasattr(module, "DummyReportResult")
    assert hasattr(module, "DummyReportCore")
    assert hasattr(module, "DummySensitivityResult")
    assert hasattr(module, "DummySensitivityCore")
    assert hasattr(module, "DummyTrendResult")
    assert hasattr(module, "DummyTrendCore")
    assert hasattr(module, "TestAnalyticsEngines")
